# Content
title: WP Pusher Checkout – Oliver – Filipe Fernandes

# Files
source: source
destination: build

# Assets
sass:
  sass_dir: styles
  style: compressed

compress:
  clippings: all
  blanklines: false
  startings: [html, head, body]
  endings: all
